project:
  type: website
  output-dir: _site
  resources:
    - CNAME
  pre-render: 
    - quarto run update_data.R

website:
  title: |
    SPECTRUM
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "People"
        href: staff/index.html
      - text: "Partners"
        href: partners/index.html
      - text: "Resources"
        menu:
          - text: "Publications"
            href: "publications/index.html#publications"
          - text: "Video & Media"
            href: "publications/index.html#video"
          - text: "Articles"
            href: "publications/index.html#articles"
          - text: "Projects"
            href: projects/index.html
      - text: "News and Events"
        href: news/index.html
      - text: "Other Consortia"
        menu:
          - text: "Home"
            href: https://spectrum-spark.github.io/website-impakt/
          - text: "SPARK"
            href: https://www.spark.edu.au/
          - text: "PRISM<sup>2</sup>"
            href: https://www.prism.edu.au
    foreground: "#F05662"
    background: "#FFFFFF"
    logo: images/logo_spectrum.png
  favicon: images/favicon.png
  page-footer:
    left: |
      For more information or to report issues, please contact <a href='mailto:spectrum-spark@unimelb.edu.au'>the consortia project inbox</a>. <br>
      © May 2023 SPECTRUM
    right: |
      Supporting Participatory Evidence generation to Control Transmissible diseases in our Region Using Modelling (SPECTRUM) <br>
      A Centre of Research Excellence (CRE) funded by the National Health and Medical Research Council (NHMRC).
    background: "#F05662"
    foreground: "#FFFFFF"
  google-analytics: "G-7WRYK2TCV9"
  cookie-consent: true

format:
  html:
    theme: cosmo
    css: [style_spectrum.css, custom_scss.scss]
    toc: true
    mainfont: 'sans-serif'